syntax = "proto3";

package thrust.velocity.v1alpha1;

import "thrust/common/v1alpha1/socket_address.proto";

option go_package = "github.com/thrustmc/thrust-proto/gen/go/thrust/velocity/v1alpha1;velocityv1alpha1";
option java_multiple_files = true;
option java_outer_classname = "BackendProto";
option java_package = "io.github.thrustmc.proto.velocity.v1alpha1";

message BackendEndpoint {
  string name = 1;
  thrust.common.v1alpha1.SocketAddress address = 2;
}

message BackendService {
  string name = 1;
  string namespace = 2;
  thrust.common.v1alpha1.SocketAddress address = 3;
  repeated BackendEndpoint endpoints = 4;
}
