syntax = "proto3";

package thrust.velocity.v1alpha1;

import "thrust/velocity/v1alpha1/backend.proto";

option go_package = "github.com/thrustmc/thrust-proto/gen/go/thrust/velocity/v1alpha1;velocityv1alpha1";
option java_multiple_files = true;
option java_outer_classname = "BackendDiscoveryServiceProto";
option java_package = "io.github.thrustmc.proto.velocity.v1alpha1";

service BackendDiscoveryService {
  rpc WatchBackends(WatchBackendsRequest) returns (stream BackendEvent);
}

message WatchBackendsRequest {}

message BackendEvent {
  EventType type = 1;
  Backend backend = 2;
}

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;
  EVENT_TYPE_ADDED = 1;
  EVENT_TYPE_REMOVED = 2;
  EVENT_TYPE_UPDATED = 3;
}
