syntax = "proto3";

package thrust.player.v1alpha1;

option go_package = "github.com/thrustmc/thrust-proto/gen/go/thrust/player/v1alpha1;playerv1alpha1";
option java_multiple_files = true;
option java_outer_classname = "GameProfileProto";
option java_package = "io.github.thrustmc.proto.player.v1alpha1";

message GameProfile {
  string id = 1;
  string name = 2;
  repeated GameProfileProperty properties = 3;
}

message GameProfileProperty {
  string name = 1;
  string value = 2;
  string signature = 3;
}
