syntax = "proto3";

package thrust.player.v1alpha1;

import "thrust/player/v1alpha1/player.proto";

option go_package = "github.com/thrustmc/thrust-proto/gen/go/thrust/player/v1alpha1;playerv1alpha1";
option java_multiple_files = true;
option java_outer_classname = "PlayerServiceProto";
option java_package = "io.github.thrustmc.proto.player.v1alpha1";

service PlayerService {
  rpc GetAllPlayers(GetAllPlayersRequest) returns (PlayerListResponse);
  rpc GetPlayer(GetPlayerRequest) returns (Player);
}

message GetAllPlayersRequest {}

message GetPlayerRequest {
  string id = 1;
}

message PlayerListResponse {
  repeated Player players = 1;
}
