syntax = "proto3";

package thrustmc.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/thrustmc/thrust-proto/gen/go/thrustmc/v1;thrustmcv1";
option java_multiple_files = true;
option java_outer_classname = "PlayerProto";
option java_package = "io.github.thrustmc.proto.v1";

message NetworkPlayer {
  string id = 1;
  string name = 2;
  string proxy_pod_name = 3;
  repeated PlayerProperty properties = 4;
  google.protobuf.Timestamp connected_at = 5;
}

message PlayerProperty {
  string name = 1;
  string value = 2;
  string signature = 3;
}
