syntax = "proto3";

package thrustmc.v1;

import "thrustmc/v1/player.proto";

option go_package = "github.com/thrustmc/thrust-proto/gen/go/thrustmc/v1;thrustmcv1";
option java_multiple_files = true;
option java_outer_classname = "PlayerServiceProto";
option java_package = "io.github.thrustmc.proto.v1";

service PlayerService {
  rpc GetAllPlayers(GetAllPlayersRequest) returns (PlayerListResponse);
  rpc GetPlayer(GetPlayerRequest) returns (NetworkPlayer);
}

message GetAllPlayersRequest {}

message GetPlayerRequest {
  string id = 1;
}

message PlayerListResponse {
  repeated NetworkPlayer players = 1;
}
